
variables:
  POSTGRES_DB: database_name

before_script:

#rails:
#  variables:
#    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
#  script:
#  - bundle exec rake db:migrate
#  - bundle exec rake db:seed
#  - bundle exec rake test


web:
  image: "jruby:9.1-jdk"
  # Cache gems in between builds
  cache:
    paths:
      - web/vendor/ruby
  artifacts:
    paths:
      - web/web-service.war

  script:
    - cd web
    - ruby -v                                   # Print out ruby version for debugging
    # Uncomment next line if your rails app needs a JS runtime:
    # - apt-get update -q && apt-get install nodejs -yqq
    - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
    - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
    - gem install warbler -v "2.0.4"

    - warble
    - mv web.war web-service.war

gui:
  image: "frekele/gradle:2.4-jdk8"
  artifacts:
    paths:
      - gui/build/libs/gui.jar

  script:
    - cp web/web-service.war gui/
    - cd gui
    - gradle build
